"""add_ktc_value_and_sleeper_projection_tables_detailed

Revision ID: 35b429fd0a4b
Revises: d3c8bfd025f7
Create Date: 2025-05-19 20:47:56.188723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '35b429fd0a4b'
down_revision: Union[str, None] = 'd3c8bfd025f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ktcvalue',
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ktc_1qb_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ktc_1qb_value', sa.Integer(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('rookie', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ktc_sf_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ktc_sf_value', sa.Integer(), nullable=True),
    sa.Column('ktc_1qb_redraft_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ktc_1qb_redraft_value', sa.Integer(), nullable=True),
    sa.Column('ktc_sf_redraft_position_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ktc_sf_redraft_value', sa.Integer(), nullable=True),
    sa.Column('ktc_value_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_ktcvalue_position'), 'ktcvalue', ['position'], unique=False)
    op.create_index(op.f('ix_ktcvalue_team'), 'ktcvalue', ['team'], unique=False)
    op.create_table('sleeperprojection',
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=True),
    sa.Column('rec_yd', sa.Float(), nullable=True),
    sa.Column('rec_td', sa.Integer(), nullable=True),
    sa.Column('rec_fd', sa.Float(), nullable=True),
    sa.Column('rec_0_4', sa.Float(), nullable=True),
    sa.Column('rec_5_9', sa.Float(), nullable=True),
    sa.Column('rec_10_19', sa.Float(), nullable=True),
    sa.Column('rec_20_29', sa.Float(), nullable=True),
    sa.Column('rec_30_39', sa.Float(), nullable=True),
    sa.Column('rec_40p', sa.Float(), nullable=True),
    sa.Column('rush_yd', sa.Float(), nullable=True),
    sa.Column('rush_td', sa.Integer(), nullable=True),
    sa.Column('rush_fd', sa.Float(), nullable=True),
    sa.Column('rush_att', sa.Integer(), nullable=True),
    sa.Column('pass_yd', sa.Float(), nullable=True),
    sa.Column('pass_td', sa.Integer(), nullable=True),
    sa.Column('pass_int', sa.Integer(), nullable=True),
    sa.Column('pass_fd', sa.Float(), nullable=True),
    sa.Column('pass_cmp', sa.Integer(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('pass_2pt', sa.Integer(), nullable=True),
    sa.Column('cmp_pct', sa.Float(), nullable=True),
    sa.Column('pts_std', sa.Float(), nullable=True),
    sa.Column('pts_ppr', sa.Float(), nullable=True),
    sa.Column('pts_half_ppr', sa.Float(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('fum_lost', sa.Integer(), nullable=True),
    sa.Column('bonus_rec_wr', sa.Float(), nullable=True),
    sa.Column('bonus_rec_te', sa.Float(), nullable=True),
    sa.Column('bonus_rec_rb', sa.Float(), nullable=True),
    sa.Column('adp_std', sa.Float(), nullable=True),
    sa.Column('adp_ppr', sa.Float(), nullable=True),
    sa.Column('adp_half_ppr', sa.Float(), nullable=True),
    sa.Column('adp_dynasty_std', sa.Float(), nullable=True),
    sa.Column('adp_dynasty_ppr', sa.Float(), nullable=True),
    sa.Column('adp_dynasty_half_ppr', sa.Float(), nullable=True),
    sa.Column('adp_dynasty_2qb', sa.Float(), nullable=True),
    sa.Column('adp_2qb', sa.Float(), nullable=True),
    sa.Column('adp_idp', sa.Float(), nullable=True),
    sa.Column('adp_rookie', sa.Float(), nullable=True),
    sa.Column('adp_dynasty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_sleeper_projection_player_season')
    )
    op.create_index(op.f('ix_sleeperprojection_player_id'), 'sleeperprojection', ['player_id'], unique=False)
    op.create_index(op.f('ix_sleeperprojection_position'), 'sleeperprojection', ['position'], unique=False)
    op.create_index(op.f('ix_sleeperprojection_season'), 'sleeperprojection', ['season'], unique=False)
    op.create_index(op.f('ix_sleeperprojection_team'), 'sleeperprojection', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeperprojection_team'), table_name='sleeperprojection')
    op.drop_index(op.f('ix_sleeperprojection_season'), table_name='sleeperprojection')
    op.drop_index(op.f('ix_sleeperprojection_position'), table_name='sleeperprojection')
    op.drop_index(op.f('ix_sleeperprojection_player_id'), table_name='sleeperprojection')
    op.drop_table('sleeperprojection')
    op.drop_index(op.f('ix_ktcvalue_team'), table_name='ktcvalue')
    op.drop_index(op.f('ix_ktcvalue_position'), table_name='ktcvalue')
    op.drop_table('ktcvalue')
    # ### end Alembic commands ###
