"""add_weekly_projection_table

Revision ID: 635ebc3e421c
Revises: d1df0b5b6b0d
Create Date: 2025-05-21 23:06:01.491719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '635ebc3e421c'
down_revision: Union[str, None] = 'd1df0b5b6b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeklyprojection',
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('opponent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('projection_date', sa.Date(), nullable=True),
    sa.Column('rush_yd', sa.Float(), nullable=True),
    sa.Column('rush_fd', sa.Float(), nullable=True),
    sa.Column('rush_att', sa.Float(), nullable=True),
    sa.Column('rec_yd', sa.Float(), nullable=True),
    sa.Column('rec_tgt', sa.Float(), nullable=True),
    sa.Column('rec_td_40p', sa.Float(), nullable=True),
    sa.Column('rec_td', sa.Float(), nullable=True),
    sa.Column('rec_fd', sa.Float(), nullable=True),
    sa.Column('rec_5_9', sa.Float(), nullable=True),
    sa.Column('rec_40p', sa.Float(), nullable=True),
    sa.Column('rec_30_39', sa.Float(), nullable=True),
    sa.Column('rec_20_29', sa.Float(), nullable=True),
    sa.Column('rec_10_19', sa.Float(), nullable=True),
    sa.Column('rec_0_4', sa.Float(), nullable=True),
    sa.Column('rec', sa.Float(), nullable=True),
    sa.Column('pts_std', sa.Float(), nullable=True),
    sa.Column('pts_ppr', sa.Float(), nullable=True),
    sa.Column('pts_half_ppr', sa.Float(), nullable=True),
    sa.Column('pos_adp_dd_ppr', sa.Integer(), nullable=True),
    sa.Column('gp', sa.Integer(), nullable=True),
    sa.Column('fum_lost', sa.Float(), nullable=True),
    sa.Column('fum', sa.Float(), nullable=True),
    sa.Column('bonus_rec_wr', sa.Float(), nullable=True),
    sa.Column('adp_dd_ppr', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at_db', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'week', 'season', name='uq_weekly_projection_player_week_season')
    )
    op.create_index(op.f('ix_weeklyprojection_game_id'), 'weeklyprojection', ['game_id'], unique=False)
    op.create_index(op.f('ix_weeklyprojection_player_id'), 'weeklyprojection', ['player_id'], unique=False)
    op.create_index(op.f('ix_weeklyprojection_season'), 'weeklyprojection', ['season'], unique=False)
    op.create_index(op.f('ix_weeklyprojection_team'), 'weeklyprojection', ['team'], unique=False)
    op.create_index(op.f('ix_weeklyprojection_week'), 'weeklyprojection', ['week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weeklyprojection_week'), table_name='weeklyprojection')
    op.drop_index(op.f('ix_weeklyprojection_team'), table_name='weeklyprojection')
    op.drop_index(op.f('ix_weeklyprojection_season'), table_name='weeklyprojection')
    op.drop_index(op.f('ix_weeklyprojection_player_id'), table_name='weeklyprojection')
    op.drop_index(op.f('ix_weeklyprojection_game_id'), table_name='weeklyprojection')
    op.drop_table('weeklyprojection')
    # ### end Alembic commands ###
