"""add_fantasy_calc_value_table

Revision ID: 7aa98fedd95b
Revises: e2e59dda9d45
Create Date: 2025-05-21 23:02:29.186189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7aa98fedd95b'
down_revision: Union[str, None] = 'e2e59dda9d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasycalcvalue',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_1qb_12team_0ppr', sa.Integer(), nullable=True),
    sa.Column('value_1qb_12team_05ppr', sa.Integer(), nullable=True),
    sa.Column('value_1qb_12team_1ppr', sa.Integer(), nullable=True),
    sa.Column('value_1qb_14team_0ppr', sa.Integer(), nullable=True),
    sa.Column('value_1qb_14team_05ppr', sa.Integer(), nullable=True),
    sa.Column('value_1qb_14team_1ppr', sa.Integer(), nullable=True),
    sa.Column('value_2qb_12team_0ppr', sa.Integer(), nullable=True),
    sa.Column('value_2qb_12team_05ppr', sa.Integer(), nullable=True),
    sa.Column('value_2qb_12team_1ppr', sa.Integer(), nullable=True),
    sa.Column('value_2qb_14team_0ppr', sa.Integer(), nullable=True),
    sa.Column('value_2qb_14team_05ppr', sa.Integer(), nullable=True),
    sa.Column('value_2qb_14team_1ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_1qb_12team_0ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_1qb_12team_05ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_1qb_12team_1ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_1qb_14team_0ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_1qb_14team_05ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_1qb_14team_1ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_2qb_12team_0ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_2qb_12team_05ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_2qb_12team_1ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_2qb_14team_0ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_2qb_14team_05ppr', sa.Integer(), nullable=True),
    sa.Column('redraft_value_2qb_14team_1ppr', sa.Integer(), nullable=True),
    sa.Column('overall_rank', sa.Integer(), nullable=True),
    sa.Column('position_rank', sa.Integer(), nullable=True),
    sa.Column('trend_30_day', sa.Integer(), nullable=True),
    sa.Column('redraft_dynasty_value_difference', sa.Integer(), nullable=True),
    sa.Column('redraft_dynasty_value_perc_difference', sa.Float(), nullable=True),
    sa.Column('combined_value', sa.Integer(), nullable=True),
    sa.Column('maybe_moving_standard_deviation', sa.Integer(), nullable=True),
    sa.Column('maybe_moving_standard_deviation_perc', sa.Float(), nullable=True),
    sa.Column('maybe_moving_standard_deviation_adjusted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_fantasycalcvalue_position'), 'fantasycalcvalue', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fantasycalcvalue_position'), table_name='fantasycalcvalue')
    op.drop_table('fantasycalcvalue')
    # ### end Alembic commands ###
