"""add_fpros_projection_table

Revision ID: d1df0b5b6b0d
Revises: 7aa98fedd95b
Create Date: 2025-05-21 23:04:10.111030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1df0b5b6b0d'
down_revision: Union[str, None] = '7aa98fedd95b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fprosprojection',
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pass_attempts', sa.Float(), nullable=True),
    sa.Column('completions', sa.Float(), nullable=True),
    sa.Column('pass_yards', sa.Float(), nullable=True),
    sa.Column('pass_tds', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Float(), nullable=True),
    sa.Column('rush_attempts', sa.Float(), nullable=True),
    sa.Column('rush_yards', sa.Float(), nullable=True),
    sa.Column('rush_tds', sa.Float(), nullable=True),
    sa.Column('receptions', sa.Float(), nullable=True),
    sa.Column('rec_yards', sa.Float(), nullable=True),
    sa.Column('rec_tds', sa.Float(), nullable=True),
    sa.Column('fumbles_lost', sa.Float(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_fprosprojection_position'), 'fprosprojection', ['position'], unique=False)
    op.create_index(op.f('ix_fprosprojection_team'), 'fprosprojection', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fprosprojection_team'), table_name='fprosprojection')
    op.drop_index(op.f('ix_fprosprojection_position'), table_name='fprosprojection')
    op.drop_table('fprosprojection')
    # ### end Alembic commands ###
