"""create_player_table

Revision ID: d3c8bfd025f7
Revises: 
Create Date: 2025-05-19 20:20:33.658826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3c8bfd025f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fantasy_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rotowire_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('player_id'),
    sa.UniqueConstraint('rotowire_id')
    )
    op.create_index(op.f('ix_player_last_name'), 'player', ['last_name'], unique=False)
    op.create_index(op.f('ix_player_player_id'), 'player', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_player_name'), 'player', ['player_name'], unique=False)
    op.create_index(op.f('ix_player_position'), 'player', ['position'], unique=False)
    op.create_index(op.f('ix_player_status'), 'player', ['status'], unique=False)
    op.create_index(op.f('ix_player_team'), 'player', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_team'), table_name='player')
    op.drop_index(op.f('ix_player_status'), table_name='player')
    op.drop_index(op.f('ix_player_position'), table_name='player')
    op.drop_index(op.f('ix_player_player_name'), table_name='player')
    op.drop_index(op.f('ix_player_player_id'), table_name='player')
    op.drop_index(op.f('ix_player_last_name'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
