"""add_clay_projection_table

Revision ID: e2e59dda9d45
Revises: 35b429fd0a4b
Create Date: 2025-05-21 22:59:10.096466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2e59dda9d45'
down_revision: Union[str, None] = '35b429fd0a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clayprojection',
    sa.Column('player_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pos_rank', sa.Integer(), nullable=True),
    sa.Column('ff_points', sa.Integer(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('pass_att', sa.Integer(), nullable=True),
    sa.Column('comp', sa.Integer(), nullable=True),
    sa.Column('pass_yds', sa.Integer(), nullable=True),
    sa.Column('pass_td', sa.Integer(), nullable=True),
    sa.Column('ints', sa.Integer(), nullable=True),
    sa.Column('sk', sa.Integer(), nullable=True),
    sa.Column('carry', sa.Integer(), nullable=True),
    sa.Column('ru_yds', sa.Integer(), nullable=True),
    sa.Column('ru_tds', sa.Integer(), nullable=True),
    sa.Column('targ', sa.Integer(), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=True),
    sa.Column('re_yds', sa.Integer(), nullable=True),
    sa.Column('re_tds', sa.Integer(), nullable=True),
    sa.Column('car_pct', sa.Integer(), nullable=True),
    sa.Column('targ_pct', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_index(op.f('ix_clayprojection_position'), 'clayprojection', ['position'], unique=False)
    op.create_index(op.f('ix_clayprojection_team'), 'clayprojection', ['team'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clayprojection_team'), table_name='clayprojection')
    op.drop_index(op.f('ix_clayprojection_position'), table_name='clayprojection')
    op.drop_table('clayprojection')
    # ### end Alembic commands ###
